# Configure the values below with the values from your application
# You can create one at hhttp://www.facebook.com/developers/apps.php
app_id: 189363111101963
secret: adeb8e7189b632e96b159da3551e17b5
api_key: 189363111101963
app_url: "http://localhost:9393" # No trailing slash
fb_app_url: "http://apps.facebook.com/189363111101963" # No trailing slash